# ==========================================
# TMUX CONFIG — KANAGAWA
# ==========================================

# Prefix
set -g prefix `
unbind C-b
bind ` send-prefix

# General
set -g base-index 1
set -g detach-on-destroy off
set -g escape-time 0
set -g renumber-windows on
set -g set-clipboard on

# Terminal
set -g default-terminal "tmux-256color"
set -ag terminal-overrides ",xterm-256color:RGB"

# Status bar
set-option -g status-position top

# Vim motions
setw -g mode-keys vi

# Mouse
set -g mouse on

# Better scrolling
bind -n WheelUpPane if -F '#{alternate_on}' 'send-keys Up' 'if -F "#{mouse_any_flag}" "send -M" "copy-mode -e; send-keys -M"'
bind -n WheelDownPane if -F '#{alternate_on}' 'send-keys Down' 'send-keys -M'

# Environment
set-environment -g TMUX_PLUGIN_MANAGER_PATH '~/.tmux/plugins'
set-environment -g PATH "/opt/homebrew/bin:/usr/local/bin:/bin:/usr/bin"

# ==========================================
# PLUGINS
# ==========================================

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-sensible'
set -g @plugin 'tmux-plugins/tmux-yank'
set -g @plugin 'omerxx/tmux-floax'

# ==========================================
# FLOAX
# ==========================================

set -g @floax-width '80%'
set -g @floax-height '80%'

# Kanagawa blue
set -g @floax-border-color '#7E9CD8'

set -g @floax-text-color '#DCD7BA'
set -g @floax-bind 'p'
set -g @floax-change-path 'true'

# ==========================================
# KANAGAWA THEME
# ==========================================

# Transparent background
set -g status-style "bg=default"

# Left side
set -g status-left-length 100
set -g status-left ""

# set -ag status-left "#[fg=#7E9CD8,bold]   "
set -ag status-left "#[fg=#DCD7BA]#S "

# Right side
set -g status-right-length 100

set -g status-right "#[fg=#76946A]%Y-%m-%d "
set -ag status-right "#[fg=#C0A36E]%H:%M "

# Window tabs
setw -g window-status-format " #[fg=#727169]#I:#W "

setw -g window-status-current-format "#[fg=#1F1F28,bg=#7E9CD8,bold] #I:#W "

setw -g window-status-style "bg=default"
setw -g window-status-current-style "fg=#1F1F28,bg=#7E9CD8"

# Pane borders
set -g pane-border-style "fg=#2A2A37"
set -g pane-active-border-style "fg=#7E9CD8"

# Messages
set -g message-style "fg=#DCD7BA,bg=#2D4F67"

# Command prompt
set -g message-command-style "fg=#DCD7BA,bg=#2D4F67"

# ==========================================
# TPM
# ==========================================

run '~/.tmux/plugins/tpm/tpm'
